### ISSUE TITLE
PackageReference support

### ISSUE THREAD

**Issue by snowhawk04** [Queuete/ExileApi#50]
Latest change to Stashie included a pull request that [migrated assembly references to packagereferences](https://github.com/nymann/Stashie/commit/e8f677ae7c7dd5374504131c3999ed6fa3827c34). @Macaddict42 has been sending these migration pull requests out and perhaps could share why the migration is necessary, what it hopes to accomplish, and any quirks that may result from migration (e.g. dependency output at plugin level instead of project level).

```
2020-10-13 00:11:25.546 -07:00 [ERR] Stashie -> Source\Stashie\FilterParser.cs(5,7) : error CS0246: The type or namespace name 'SharpDX' could not be found (are you missing a using directive or an assembly reference?)
2020-10-13 00:11:25.546 -07:00 [ERR] Stashie -> Source\Stashie\FilterResult.cs(1,7) : error CS0246: The type or namespace name 'SharpDX' could not be found (are you missing a using directive or an assembly reference?)
2020-10-13 00:11:25.546 -07:00 [ERR] Stashie -> Source\Stashie\ItemData.cs(6,7) : error CS0246: The type or namespace name 'SharpDX' could not be found (are you missing a using directive or an assembly reference?)
2020-10-13 00:11:25.546 -07:00 [ERR] Stashie -> Source\Stashie\Refill.cs(6,7) : error CS0246: The type or namespace name 'SharpDX' could not be found (are you missing a using directive or an assembly reference?)
2020-10-13 00:11:25.546 -07:00 [ERR] Stashie -> Source\Stashie\Stashie.cs(17,33) : error CS0234: The type or namespace name 'Vector4' does not exist in the namespace 'System.Numerics' (are you missing an assembly reference?)
2020-10-13 00:11:25.546 -07:00 [ERR] Stashie -> Source\Stashie\Stashie.cs(16,7) : error CS0246: The type or namespace name 'SharpDX' could not be found (are you missing a using directive or an assembly reference?)
2020-10-13 00:11:25.546 -07:00 [ERR] Stashie -> Source\Stashie\Filter\BaseFilter.cs(2,7) : error CS0246: The type or namespace name 'JM' could not be found (are you missing a using directive or an assembly reference?)
2020-10-13 00:11:25.547 -07:00 [ERR] Stashie -> Source\Stashie\FilterResult.cs(18,16) : error CS0246: The type or namespace name 'Vector2' could not be found (are you missing a using directive or an assembly reference?)
2020-10-13 00:11:25.547 -07:00 [ERR] Stashie -> Source\Stashie\ItemData.cs(43,16) : error CS0246: The type or namespace name 'Vector2' could not be found (are you missing a using directive or an assembly reference?)
2020-10-13 00:11:25.547 -07:00 [ERR] Stashie -> Source\Stashie\ItemData.cs(111,16) : error CS0246: The type or namespace name 'Vector2' could not be found (are you missing a using directive or an assembly reference?)
2020-10-13 00:11:25.547 -07:00 [ERR] Stashie -> Source\Stashie\ItemData.cs(116,16) : error CS0246: The type or namespace name 'Vector2' could not be found (are you missing a using directive or an assembly reference?)
2020-10-13 00:11:25.547 -07:00 [ERR] Stashie -> Source\Stashie\Refill.cs(128,16) : error CS0246: The type or namespace name 'Vector2' could not be found (are you missing a using directive or an assembly reference?)
2020-10-13 00:11:25.547 -07:00 [ERR] Stashie -> Source\Stashie\Refill.cs(130,16) : error CS0246: The type or namespace name 'Point' could not be found (are you missing a using directive or an assembly reference?)
2020-10-13 00:11:25.547 -07:00 [ERR] Stashie -> Source\Stashie\Stashie.cs(949,24) : error CS0246: The type or namespace name 'Vector2' could not be found (are you missing a using directive or an assembly reference?)
2020-10-13 00:11:25.547 -07:00 [ERR] Stashie -> Source\Stashie\Stashie.cs(956,52) : error CS0246: The type or namespace name 'Vector2' could not be found (are you missing a using directive or an assembly reference?)
2020-10-13 00:11:25.547 -07:00 [ERR] Stashie -> Source\Stashie\Stashie.cs(956,66) : error CS0246: The type or namespace name 'Vector2' could not be found (are you missing a using directive or an assembly reference?)
2020-10-13 00:11:25.547 -07:00 [ERR] Stashie -> Source\Stashie\Stashie.cs(1113,42) : error CS0246: The type or namespace name 'Vector2' could not be found (are you missing a using directive or an assembly reference?)
2020-10-13 00:11:25.547 -07:00 [ERR] Stashie -> Source\Stashie\Stashie.cs(1125,41) : error CS0246: The type or namespace name 'Vector2' could not be found (are you missing a using directive or an assembly reference?)
2020-10-13 00:11:25.547 -07:00 [ERR] Stashie -> Source\Stashie\Stashie.cs(32,17) : error CS0246: The type or namespace name 'Vector2' could not be found (are you missing a using directive or an assembly reference?)
```

**Comment by Macaddict42** [comment]
packages.config for nuget is now deprecated, as it is fundamentally flawed. It is tied to the solution and not to the packages themselves. This means resolving packages is almost always broken when a project is included in more than one solution and when the directory structure varies. PackageReference fixes all of these and reduces the number of files downloaded to your system because it uses a global package cache instead of downloading the packages to your solution directory. 

Regarding the errors you're listed. The important thing to do is to use PackageReference and verify that plugins are referencing the ExileApi project and not the DLL file itself. That will ensure that everything is linked up properly together.

**Comment by snowhawk04** [comment]
The errors I listed are because the compiler doesn't process "PackageReference" references resulting in missing references.

**Comment by Macaddict42** [comment]
Does require VS2019 (mayyyyybe latest VS2017), you using something older?

**Comment by Macaddict42** [comment]
https://docs.microsoft.com/en-us/nuget/consume-packages/migrate-packages-config-to-package-reference

Works with VS2017 if you update to 15.7+

**Comment by snowhawk04** [comment]
It compiles fine if I manually compile it through VS. It doesn't compile through the autoupdater because `PackageReference`s aren't processed. You can see what reference tags are processed below.

https://github.com/Queuete/ExileApi/blob/59598db132356ed5f28353d3dc43ddb5c354c7ba/Core/Shared/PluginAutoUpdate/PluginCompiler.cs#L106-L152

**Comment by Macaddict42** [comment]
Oh right because it uses the msbuild package to do that. Just needs to update that dependency.

**Comment by Macaddict42** [comment]
Nevermind, just looks at that code. Ya it's a little weird. Would need to be updated to work with the <PackageReferece> tag.

**Comment by snowhawk04** [comment]
@Macaddict42 when you compile plugins that have been migrated from packages.config to PackageReference, does compilation result in every reference existing in the plugin folder?

**Comment by Macaddict42** [comment]
Yes, because I only build with VS and don't rely on the auto-update build. I'm a plugin developer so I already have a full environment setup for my needs.

**Comment by Macaddict42** [comment]
You have to realize that the PluginAutoUpdate feature was not created or supported by TehCheat. Meanwhile, development of plugins continues to progress while targeting his now-private repo. This repo is effectively dead and will not continue to receive support.

**Comment by snowhawk04** [comment]
Ignore autoupdate. When manually compiling through visual studio, should the plugin be copying every reference locally? 

![download](https://user-images.githubusercontent.com/6187693/95924122-ce602000-0d6b-11eb-9c4a-bf2309c5bca8.png)

With packages.config, we had the option to prevent local copies with by setting the Private property to false.

https://github.com/nymann/Stashie/blob/7562a351d547ce650b5179254b67e0258ece8611/Stashie.csproj#L73-L76

Anyway, this issue of excessive local copying is more of a PackageReference migration issue with Stashie than it is an issue with the Core compiler or ExileHud.

**Comment by Macaddict42** [comment]
This is not an issue, this is standard behavior for Nuget packages.

https://docs.microsoft.com/en-us/nuget/consume-packages/package-references-in-project-files

**Comment by Macaddict42** [comment]
You can resolve this by adding <PrivateAssets>all</PrivateAssets> to the PackageReferences in Core and adding <ExcludeAssets>runtime</ExcludeAssets> to the PackageReferences in whatever plugin you're using (Stashie).

**Comment by Queuete** [comment]
The AutoUpdater started out with the "compilePlugins.bat" in mind when it started. The current parsing of the references is only the result of a slight rework of those ideas.
Using a full build environment would be the more stable solution but is not easily possible. Nevertheless the nuget references should be processed aswell and I will look into this.

@Macaddict42 While your developement targets the private repository of TehCheat thats not the case for all plugin developers. As long as there is no public access to his repo I dont see any reason why this fork should be irrelevant or "effectively dead", there are quite a lot of people using this branch according to the download numbers of the releases.

**Comment by snowhawk04** [comment]
> You can resolve this by adding <PrivateAssets>all</PrivateAssets> to the PackageReferences in Core and adding <ExcludeAssets>runtime</ExcludeAssets> to the PackageReferences in whatever plugin you're using (Stashie).

Shouldn't the stashie change been part of its commit? 

> This is not an issue, this is standard behavior for Nuget packages.

I get that it's the default behavior when you press the "Migrate to PackageReference" option for a project, but that isn't the behavior this project, no matter the fork or plugin, was configured for when using Packages.config. In fact, every other developer has gone out of their way to make sure libraries aren't being copied to every plugin. TehCheat pushed a change a week ago that [added a reference to Pickit that specifically disables local copying of that library](https://github.com/TehCheat/Pickit/blob/c16ac5b3a4cd9e86448449e882bfbe752ea89d14/PickIt.csproj#L77-L81).

Imagine every plugin just hitting that "Migrate to PackageReference" option in VS and we went with the default behavior. It would be pretty bad, right? This is rhetorical, you don't have to answer.

I was trying to figure out where this motivation to migrate came from mainly because NOBODY ELSE IS MIGRATING. Neither of the maintainers have shown they are migrating. TehCheat let your pull requests rot before deciding to go private. But hey, maybe he accepted it since. I believe Stashie is the only plugin repository that has accepted your migration pull request.

> packages.config for nuget is now deprecated

I'm going to need a citation on this.

**Comment by nymann** [comment]
The change to Stashie also introduced the idea of not targeting the `ExileCore.dll` but instead adding it as a project reference. I personally dislike this idea since it makes it harder for people that do not have access to the private ExileApi repository to contribute to Stashie.
